name: "9.0.1"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/c71f061c68ba8ce53471b767d5049cbd0f3d8490.tar.gz

      - name: Compile
        run: nix-shell nix/ghc_9-0-1.nix --command "cabal build"

      - name: Test
        run: nix-shell nix/ghc_9-0-1.nix --command "cabal test"