name: style

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/931ab058daa7e4cd539533963f95e2bb0dbd41e6.tar.gz

      - name: cabal-fmt
        run: nix-shell nix/ci.nix --pure --command "bash ./ci_scripts/cabal-fmt.sh"

      - name: hlint
        run: nix-shell nix/ci.nix --pure --command "bash ./ci_scripts/hlint.sh"

      - name: ormolu
        run: nix-shell nix/ci.nix --pure --command "bash ./ci_scripts/ormolu.sh"

      - name: nixpkgs-fmt
        run: nix-shell nix/ci.nix --pure --command "bash ./ci_scripts/nixpkgs-fmt.sh"
